theme = "nord"

[editor]
auto-format = false
auto-completion = false
scrolloff = 5

[editor.cursor-shape]
insert = "bar"
normal = "block"

[keys.normal]
"A-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "move_line_up"]
"A-down" = ["extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before", "move_line_up"]
"C-ret" = ["open_below", "normal_mode"]
"C-S-ret" = ["open_above", "normal_mode"]

[keys.insert]
# k = { j = "normal_mode" }
# j = { k = "normal_mode" }
"A-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "move_line_up"]
"A-down" = ["extend_to_line_bounds", "delete_selection", "move_line_down", "paste_before", "move_line_up"]
"A-S-up" = ["extend_to_line_bounds", "yank", "paste_before"]
"A-S-down" = ["extend_to_line_bounds", "yank", "move_line_down", "paste_before", "move_line_up"]
"C-ret" = ["open_below"]
"C-S-ret" = ["open_above"]
