[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi"]
shebangs = ["python"]
auto-format = false
roots = ["venv/"]
comment-token = "#"
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = """
{
  "python": {
    "analysis": {
      "autoSearchPaths": true,
      "diagnosticMode": "workspace"
    }
  }
}
"""
# TODO: pyls needs utf-8 offsets
indent = { tab-width = 4, unit = "    " }